---
title: "GDP and Education"
author: "Sharon Teo"
date: "June 19, 2016"
output: 
  html_document:
    keep_md: yes
---
```{R global_options, include=FALSE}
knitr::opts_chunk$set(warning=FALSE, message=FALSE)
```

# Libraries required
```{R}
library(repmis)
library(RCurl)
library(bitops)
library(ggplot2)
library(downloader)
library(dplyr)
```

# Introduction
The purpose of this project is to visualize GDP across countries and income groups using the dataset  provided by client. The data set comes from worldbank.org. The first data set consists of gross domestic product ranking by countries for economies around the world while the second data set consists of education statistics and income levels. R is used to clean, merge the two files together, analyze and summarize the findings from the given data set.

# Download files from World Bank website
```{R}
site="https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FGDP.csv" 
download.file(site,destfile="./getdata%2Fdata%2FGDP.csv")
site="https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FEDSTATS_Country.csv" 
download.file(site,destfile="./getdata%2Fdata%2FEDSTATS_Country.csv")
```

# Read the files into R
```{R}
GDP <- read.csv("getdata%2Fdata%2FGDP.csv",header=TRUE)
EDU <- read.csv("getdata%2Fdata%2FEDSTATS_Country.csv", header=FALSE)
```

# Data cleansing
```{R}
GDP <- read.csv("getdata%2Fdata%2FGDP.csv", stringsAsFactors=FALSE, header=TRUE)
GDPraw <- GDP
# Remove redundant columns from GDPraw data set
GDPraw[6:10] <-list(NULL)
GDPraw$X.1 <- NULL
GDPdata <- GDPraw[5:330,]
# Assign new headings to GDPdata
names(GDPdata) <- c("Country.Code", "Ranking", "Short.Name", "GDP")
GDPdata$Ranking <- as.numeric(GDPdata$Ranking)
# Remove commas from GDP
GDPdata$GDP <- gsub(",","",GDPdata$GDP)
# Convert GDP to numeric
GDPdata$GDP <- as.numeric(GDPdata$GDP)
head(GDPdata)
EDUraw <- EDU
# Remove redundant columns from EDUraw data set
EDUraw[4:30] <-list(NULL)
EDUraw[2] <- NULL
EDUdata <- EDUraw[2:240,]
# Assign new headings to EDUdata
names(EDUdata) <- c("Country.Code", "Income.Group", "Short.Name")
head(EDUdata)
# Merge GDP and EDU
GDPEDU <- merge(GDPdata,EDUdata,by="Country.Code")
head(GDPEDU)
```

# Match the data based on the country shortcode. How many of the IDs match?  
##224
```{R}
summary(GDPEDU)
```

# Sort the data frame in ascending order by GDP rank (so United States is last). What is the 13th country in the resulting data frame?  
##St. Kitts and Nevis is the 13th country
```{R}
#sort by GDP (ascending)
NEWGE <- GDPEDU[order(GDPEDU$GDP),] 
#We See There is 14 blank Income Groups
NEWGE=subset(NEWGE, NEWGE$Income.Group!="")
NEWGE=subset(NEWGE, NEWGE$Income.Group!="Income Group")
NEWGE[1:13,1:5]
```
# What are the average GDP rankings for the "High income: OECD" and "High income: nonOECD" groups? 
##High Income OECD=$1483917 High Income: nonOECD=$104350
```{R}
#Taking a subset of data that consist only of income in High OECD and nonOECD
HOECD=subset(NEWGE,NEWGE$Income.Group=='High income: OECD')
HNOECD=subset(NEWGE,NEWGE$Income.Group=='High income: nonOECD')
summary(HOECD)
summary(HNOECD)
```
# Plot the GDP for all of the countries. Use ggplot2 to color your plot by Income Group.

```{R}
plot(NEWGE$Ranking,log(NEWGE$GDP),xlab="Rank",ylab="GDP",main="GDP Across Country Rankings")
INC.TAB=table(NEWGE$Income.Group)
INC.TAB
barplot(INC.TAB,xlab="",ylab="Counts",main="GDP Across Country Rankings",col=rainbow(7),las=3,cex.names = .45)


# Shows the breakdown across country ranking, color coded by income group
qplot(as.numeric(NEWGE$Ranking), data=NEWGE, geom="bar", weight=log(NEWGE$GDP), ylab="GDP",xlab="Ranking",main = "GDP According to Country Rank",fill=NEWGE$Income.Group)+
theme(axis.text.x=element_text(angle=90,hjust=1,vjust=0.5))

g = ggplot(NEWGE, aes(x = as.numeric(NEWGE$Ranking), y=log(NEWGE$GDP)))  + geom_point()+
aes(colour = NEWGE$Income.Group)+
labs(x="Rank",y="Natural Log GDP")+ 
theme(axis.text.x=element_text(angle=90,hjust=1,vjust=0.5))

g
```

#Cut the GDP ranking into 5 separate quantile groups. Make a table versus Income.Group. How many countries are Lower middle income but among the 38 nations with highest GDP?
##3

```{R}
#Breaks the data set in slices according to GDP. Divide countries into five groups by GDP. 1(low income) reflects the lowest tier of GDP and 5 is highest(wealthy nations)
NEWGE$quantile <- ntile(NEWGE$GDP, 5)
table(NEWGE$quantile,NEWGE$Income.Group)
```

# Conclusion
## In conclusion we see that GDP and income groups do not sync up properly.     There is incongruity between the two variables. We would expect that there    would be more high income groups in the highly ranked countries, but it was    not the case in all situations. After visualizing the data it was clear that  there are countries that fall into low income groups yet are in the top 20    percent of GDP. Additional data recording is needed for a more through        representation of countries wealth/prosperity in a global context.

